-- Aula 05 · Data Visualization · 12/09/2026 · retomada das Aulas 01–04.
-- Usa as tabelas/RPCs existentes no Supabase do aulas_senac. Não execute o schema destrutivo.
-- Reexecução preserva IDs; recusa alterar sala iniciada ou com participantes.
begin;
select pg_advisory_xact_lock(hashtext('mack-dv-a05-2026-2'));
do $$ begin if exists (select 1 from quiz_sessions where slug='mack-dv-a05-2026-2' and (estado <> 'lobby' or pergunta_atual <> 0)) or exists (select 1 from quiz_players where session_slug='mack-dv-a05-2026-2') then raise exception 'Sala já iniciada ou com participantes: seed cancelado para preservar a rodada.'; end if; end $$;
insert into quiz_sessions (slug,titulo,periodo) values ('mack-dv-a05-2026-2','Aula 05 — Retomada: Data Visualization','2026-2') on conflict (slug) do update set titulo=excluded.titulo;
with novas as (
  insert into quiz_questions (session_slug,ordem,enunciado,alternativas,segundos,tema,secao,peso) values
  ('mack-dv-a05-2026-2', 1, 'Antes de calcular o ticket médio no Metabase, a equipe encontra valores nulos e várias linhas com o mesmo order_id. Qual é o primeiro passo para interpretar esses dados?', '["Excluir os nulos e manter uma linha por order_id para obter uma base sem repetições.", "Calcular a média e usar o resultado como referência para decidir quais linhas remover.", "Identificar o grão de cada tabela e verificar nulos, chaves e relações antes de definir a métrica.", "Montar o dashboard por mês e investigar a estrutura somente se houver valores extremos."]'::jsonb, 90, 'Data discovery e grão', 'Aula 01 — perfil das tabelas, nulos e grão', 1),
  ('mack-dv-a05-2026-2', 2, 'Na fato de itens do Olist, um pedido contém três produtos. Qual contrato de grão permite validar a unicidade sem descartar itens válidos?', '["Uma linha por combinação de order_id e order_item_id.", "Uma linha por order_id, conservando somente o primeiro produto.", "Uma linha por product_id, somando as compras de todos os clientes.", "Uma linha por cliente e mês, reunindo os pedidos do período."]'::jsonb, 90, 'Modelagem dimensional', 'Aula 02 — fato item de pedido; Aula 04 — mart e grão', 1),
  ('mack-dv-a05-2026-2', 3, 'Um pedido tem três itens e duas linhas de pagamento. O join entre as duas tabelas usa apenas order_id e produz seis linhas. Como comparar os totais de itens e pagamentos sem inflá-los?', '["Somar os valores nas seis linhas, pois o join já preservou o vínculo com o pedido.", "Trocar o INNER JOIN por LEFT JOIN para que cada item apareça uma única vez.", "Aplicar SUM(DISTINCT price), assumindo que preços iguais representam o mesmo item.", "Agregar cada fato por pedido antes de combiná-las nesse grão comum."]'::jsonb, 90, 'Fanout e reconciliação', 'Aula 02 — fanout e drill-across; Aula 04 — mart sem multiplicar receita', 1),
  ('mack-dv-a05-2026-2', 4, 'Uma gestora quer comparar a receita de cinco categorias no mesmo período. Qual representação responde diretamente a essa tarefa de magnitude?', '["Uma linha ligando as categorias em ordem alfabética, destacando a continuidade entre elas.", "Barras com uma base comum em zero, mantendo a mesma unidade e o mesmo recorte.", "Um histograma da receita, tratando cada categoria como um intervalo numérico.", "Uma dispersão das categorias, usando sua posição na lista como variável horizontal."]'::jsonb, 90, 'Magnitude e integridade numérica', 'Aula 03 — magnitude: barras e suas regras', 1),
  ('mack-dv-a05-2026-2', 5, 'Dois histogramas usam os mesmos prazos de entrega. Com intervalos de um dia aparecem vários picos; com intervalos de dez dias aparece um único bloco dominante. O que essa diferença permite afirmar?', '["Que os prazos foram alterados na segunda consulta, pois os picos deveriam permanecer iguais.", "Que o intervalo de dez dias é o correto, pois produz uma distribuição visualmente mais simples.", "Que a largura dos intervalos muda a leitura; é preciso conferir limites, contagens e sensibilidade ao agrupamento.", "Que o histograma deve ser substituído pela média, pois a distribuição depende de uma escolha visual."]'::jsonb, 90, 'Distribuição e intervalos', 'Aula 03 — distribuição: histograma e escolha do intervalo', 1),
  ('mack-dv-a05-2026-2', 6, 'No Olist, pedidos com frete maior também apresentam maior prazo de entrega. O gráfico de dispersão, sozinho, sustenta qual leitura?', '["Há associação no recorte; distância, região e outras variáveis precisam ser examinadas antes de atribuir causa.", "Aumentar o frete causa maior prazo, porque a inclinação aparece nos pontos observados.", "Reduzir o frete reduzirá o prazo na mesma proporção, mantendo o restante da operação.", "A associação deixa de existir se a equipe não encontrar imediatamente uma explicação causal."]'::jsonb, 90, 'Relação e limites da evidência', 'Aula 03 — dispersão, correlação e agregação', 1),
  ('mack-dv-a05-2026-2', 7, 'No fluxo Excel → SQLite → HTML, o relatório abre normalmente, mas o total de pedidos foi digitado como uma constante no código. Qual correção atende ao contrato da Aula 04?', '["Manter o número fixo e atualizar a legenda com a data em que ele foi conferido.", "Gerar o total por uma consulta ao banco e reconciliar o resultado antes de publicar o HTML.", "Copiar o total da planilha para outra constante e comparar as duas na execução.", "Mover o número para um arquivo de configuração para separar o dado do código."]'::jsonb, 90, 'Rastreabilidade e publicação', 'Aula 04 — transformação com rastro e origem do relatório', 1),
  ('mack-dv-a05-2026-2', 8, 'A equipe anexou o arquivo SQLite no DuckDB e já consegue consultá-lo. Para criar a cópia analítica própria prevista na Aula 04, o que ainda falta?', '["Renomear a extensão do arquivo SQLite para .duckdb, preservando as tabelas existentes.", "Gerar o segundo HTML diretamente do SQLite e registrar DuckDB no título do relatório.", "Executar apenas ANALYZE sobre a conexão, pois estatísticas convertem o armazenamento da fonte.", "Materializar as tabelas no arquivo DuckDB e reconciliar as contagens com a origem."]'::jsonb, 90, 'Anexar e materializar', 'Aula 04 — mudança de mecanismo: SQLite para DuckDB', 1),
  ('mack-dv-a05-2026-2', 9, 'Um pedido tem itens em duas categorias. O mart mostra 1 pedido distinto em cada categoria. Para obter o total de pedidos do período, qual procedimento evita dupla contagem?', '["Calcular COUNT(DISTINCT order_id) na fato de itens, com os filtros do período consultado.", "Somar os distintos das categorias, porque cada linha do mart representa uma categoria diferente.", "Usar o maior total entre as categorias, pois os pedidos compartilhados aparecem no grupo maior.", "Dividir a soma pelo número de categorias, pois um pedido pode conter várias delas."]'::jsonb, 90, 'Medidas não aditivas', 'Aula 04 — contrato do mart: pedidos e ticket no grão consultado', 1),
  ('mack-dv-a05-2026-2', 10, 'O DuckDB executou uma consulta mais rápido que o SQLite em uma medição. Para produzir a evidência de desempenho pedida na Aula 04, qual é o próximo passo?', '["Publicar que DuckDB é mais rápido para qualquer carga, usando essa execução como demonstração.", "Escolher a execução mais rápida de cada banco e comparar apenas os menores tempos observados.", "Repetir a mesma consulta em ambos, separar execuções frias e aquecidas, registrar a mediana e delimitar a conclusão à carga e à máquina.", "Aumentar o volume de dados só no SQLite, para compensar a diferença entre os mecanismos."]'::jsonb, 90, 'Benchmark e evidência', 'Aula 04 — perfil antes de afirmar desempenho', 2)
  on conflict (session_slug,ordem) do update set enunciado=excluded.enunciado, alternativas=excluded.alternativas, segundos=excluded.segundos, tema=excluded.tema, secao=excluded.secao, peso=excluded.peso
  returning id,ordem
)
insert into quiz_answer_key (question_id,correta,explicacao)
select n.id,g.correta,g.explicacao from novas n join (values
  (1, 2, 'O mesmo order_id pode aparecer em várias linhas porque a tabela registra itens ou pagamentos. O perfil identifica o que uma linha representa e como os nulos afetam a pergunta. Excluir ou deduplicar antes dessa leitura pode eliminar registros válidos.'),
  (2, 0, 'A fato de itens registra um item dentro de um pedido. A combinação order_id + order_item_id identifica essa ocorrência. Pedido, produto ou cliente-mês representam outros grãos e mudam o significado das medidas.'),
  (3, 3, 'O join produz 3 × 2 combinações: cada item reaparece para cada pagamento. Pré-agregar as duas fatos por pedido evita essa multiplicação na comparação. SUM(DISTINCT price) também eliminaria itens diferentes que tivessem o mesmo preço.'),
  (4, 1, 'Barras com base comum permitem comparar comprimentos entre categorias. Cortar o eixo distorce a razão visual. Uma linha sugere continuidade, um histograma descreve uma distribuição e uma dispersão compara duas variáveis numéricas.'),
  (5, 2, 'A largura dos intervalos controla o nível de detalhe visível no histograma. Uma mudança de forma não prova mudança nos registros. Conferir limites, contagens e mais de uma largura ajuda a distinguir padrões persistentes de efeitos do agrupamento.'),
  (6, 0, 'A dispersão permite observar associação entre duas variáveis. Ela não isola fatores como distância e região nem demonstra o efeito de uma intervenção no preço do frete. O recorte e a estratificação precisam ser examinados antes de uma interpretação causal.'),
  (7, 1, 'O HTML deve publicar resultados de consultas registradas no script. Uma constante pode continuar parecendo correta mesmo depois que a base muda. Executar a consulta e reconciliar o resultado estabelece o vínculo entre entrada, transformação e saída.'),
  (8, 3, 'Anexar permite consultar dados que permanecem fisicamente no SQLite. Materializar com CREATE TABLE AS SELECT cria tabelas no arquivo DuckDB. A reconciliação verifica se essa cópia conservou os registros; mudar a extensão ou gerar estatísticas não faz a cópia.'),
  (9, 0, 'Contagens distintas não são aditivas entre grupos sobrepostos. O pedido que contém itens de duas categorias seria contado duas vezes na soma. O total precisa ser recalculado com DISTINCT no recorte final, usando a fato que conserva order_id.'),
  (10, 2, 'O protocolo usa a mesma pergunta, cinco execuções em cada banco, separação entre execução fria e aquecida e registro da mediana. A comparação precisa preservar também resultados equivalentes. Ela sustenta uma conclusão sobre essa carga no Codespace, não um vencedor universal.')
) as g(ordem,correta,explicacao) on g.ordem=n.ordem
on conflict (question_id) do update set correta=excluded.correta, explicacao=excluded.explicacao;
insert into quiz_host_tokens (session_slug,token) values ('mack-dv-a05-2026-2','__QUIZ_HOST_TOKEN__') on conflict (session_slug) do update set token=excluded.token;
do $$ begin if (select count(*) from quiz_questions where session_slug='mack-dv-a05-2026-2') <> 10 then raise exception 'A sala deve conter exatamente 10 perguntas'; end if; end $$;
commit;
